### ISSUE TITLE
Exception in barman check during database restart

### ISSUE THREAD

**Issue by danbst** [2ndquadrant-it/barman#90] opened 2017-03-06 23:32 UTC
I was running `watch -n0 barman check live` for a streaming-only setup. During that I've restarted database, it produced the following exception in logs:
```
2017-03-06 23:26:31,959 [11248] barman.postgres WARNING: Error retrieving PostgreSQL status: connection already closed
2017-03-06 23:26:31,961 [11248] barman.postgres WARNING: Error retrieving PostgreSQL status: FATAL:  the database system is shutting down
2017-03-06 23:26:31,968 [11248] barman.server ERROR: Check 'PostgreSQL' failed for server 'live'
2017-03-06 23:26:31,971 [11248] barman.server ERROR: Check 'pg_basebackup compatible' failed for server 'live'
2017-03-06 23:26:31,973 [11248] barman.server ERROR: Check 'pg_receivexlog compatible' failed for server 'live'
2017-03-06 23:26:31,974 [11248] barman.cli ERROR: connection already closed
See log file for more details.
Traceback (most recent call last):
  File "/nix/store/gb5lafd44lidzjfgy6l4v4p2alfvn5mw-barman-2.1/lib/python2.7/site-packages/barman/cli.py", line 1041, in main
    p.dispatch(pre_call=global_config)
  File "/nix/store/5q9scis96j93hwyb8njs3vj66q4p94mh-python2.7-argh-0.26.1/lib/python2.7/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/nix/store/5q9scis96j93hwyb8njs3vj66q4p94mh-python2.7-argh-0.26.1/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/nix/store/5q9scis96j93hwyb8njs3vj66q4p94mh-python2.7-argh-0.26.1/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/nix/store/5q9scis96j93hwyb8njs3vj66q4p94mh-python2.7-argh-0.26.1/lib/python2.7/site-packages/argh/dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "/nix/store/gb5lafd44lidzjfgy6l4v4p2alfvn5mw-barman-2.1/lib/python2.7/site-packages/barman/cli.py", line 517, in check
    server.check()
  File "/nix/store/5y182v03vgahackh33m1s1x4b27d4c6z-python-2.7.13/lib/python2.7/contextlib.py", line 154, in __exit__
    self.thing.close()
  File "/nix/store/gb5lafd44lidzjfgy6l4v4p2alfvn5mw-barman-2.1/lib/python2.7/site-packages/barman/server.py", line 388, in close
    self.postgres.close()
  File "/nix/store/gb5lafd44lidzjfgy6l4v4p2alfvn5mw-barman-2.1/lib/python2.7/site-packages/barman/postgres.py", line 164, in close
    self._conn.rollback()
InterfaceError: connection already closed
2017-03-06 23:26:31,975 [11248] barman.postgres WARNING: Forcing PostgreSQLConnection cleanup during process shut down.
```

**Comment by gbartolini** [comment] 2018-05-10 22:54
I have not been able to reproduce the issue. By investigating the code, it looks like the following commits have fixed it:

* 68dcdd0fce9c9d9372393c5572167d9e22ae6f50
* 49bd010dd57c1132bd46869d8ec74b03affbd613

@danbst Could you please retry and verify that this issue has been fixed? Thanks.

**Comment by gbartolini** [comment] 2018-05-11 12:51
We confirm that the issue has been fixed by the above commits. @leonardoce did some testings on the 2.1 branch and was able to reproduce the issue, which now does not happen anymore.

**Closed by gbartolini** 2018-05-11 12:51 UTC
Labels: bug, invalid
