### ISSUE TITLE
Barman backup status "changed from WAITING_FOR_WALS to FAILED"

### ISSUE THREAD

**Issue by trekker63** [2ndquadrant-it/barman#244] opened 2019-10-17 16:17 UTC
HI,

I have a Barman Server that backs up several Postgres database on different servers.
Often, but not always, only the backup of a specific Postgres Database fails with "status changed from WAITING_FOR_WALS to FAILED".

Barman version is 2.7, Postgres Version is 11.5. 

I include barman diagnose. The problem is on pg64infolog-prod.
[barman_diagnose.txt](https://github.com/2ndquadrant-it/barman/files/3740285/barman_diagnose.txt)

Thanks in advance to anyone who might give a suggestion

Marco

**Comment by bluthg** [comment] 2019-10-20 14:58
I've just stumbled across this too (a streaming only server), and boiled it down to wal_archiver.py +881 (Barman 2.9):
```
 def get_next_batch(self):
  .... snip ....
# Keep the last full WAL file in case no partial file is present
        elif len(skip) == 0 and files:
            skip.append(files.pop())
```

So, on an idle DB server (not enough activity for the walreceiver to have openend a new .partial file yet), the last streamed WAL (which in this case happens to be the crucial one containing the backup info, see "stop_backup()" comment in backup_executor.py) doesn't get sorted away and thus is "missing" when the backup is checked.

Fixing this will not be trivial (we can't just copy it to "skip" instead of moving/popping it there), as the next cron run would then unlink it.

IMHO, the proper way to do it would be to have a check if the missing segment in backup.py line 1095ff. (again, 2.9) is the only one existing in "streaming" and if so, not add it to "missing_wal".

**Comment by bluthg** [comment] 2019-10-21 21:11
Or trigger a second pg_switch_wal() when we're a streaming-only archiver?

**Comment by bluthg** [comment] 2019-10-21 22:35
Nope, that doesn't help, as then the last WAL of the backup is the one we triggered (tried it).

**Comment by fluca1978** [comment] 2019-10-22 08:38
Link to thread on mailing list <https://groups.google.com/d/msg/pgbarman/-8zYzBCuTSQ/SoAmOZFECQAJ> that shows also the logs.

**Comment by gbartolini** [comment] 2019-10-24 15:16
As explained in the mailing list thread, the issue is not a Barman bug. The Barman directory was erroneously reused by the instance after an upgrade. It should have been a separate server in the Barman installation.

In order to prevent this from happening, we will add the system identifier to a Barman installation (see #246). We will also add a note in the documentation before we close this issue.

**Closed** 2019-10-24 15:53 UTC
